### ISSUE TITLE
Dev doc `"undefined"` background image selection got interpreted as a string

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-react-component-library#717] opened 2023-03-01 13:46 UTC
## Describe the bug / expected behavior

For components with a `backgroundImage` prop, such as the Drawer Header and App Bar, whenever the backgroundImage prop is set to "undefined" in the playground dropdown selection, the console flashes a 404 warning because it cannot locate an image called "undefined".

## What are the steps to reproduce?

1. Go to [Dev Doc drawer header](https://brightlayer-ui-components.github.io/react-dev/components/drawer-header/playground) or [Dev Doc Appbar](https://brightlayer-ui-components.github.io/react-dev/components/app-bar/playground)
2. Open the console

## Screenshot

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/8997218/222152122-32c19d11-9af9-4171-92d1-2141263e2ecc.png">

## Suggested fix

Likely a wrong interpretation on the dev doc side to retrieve a non-existent image located at "https://brightlayer-ui-components.github.io/react-dev/undefined"

We might need to change this switch statement so that when the background image is a string literal `"undefined"`, we actually pass `undefined` to our components

https://github.com/etn-ccis/blui-react-component-library/blob/74871489a7397e3eac6eb6e771f4f800f7cfb6f6/docs/src/shared/utilities.tsx#L158-L169

## Anything else to add?
The icons dropdown selection seems to be working fine. This issue only exists for the background image selection.

**Comment by JeffGreiner-eaton** [comment] 2023-03-31 14:38
@huayunh I'm unable to reproduce this issue today.

**Comment by huayunh** [comment] 2023-03-31 14:49
I am still seeing it after emptying my cache

![image](https://user-images.githubusercontent.com/8997218/229153944-6c14cc84-ae13-4f18-ba75-2809e2e9f09b.png)

**Comment by JeffGreiner-eaton** [comment] 2023-03-31 15:33
Odd I have no issues on my with chrome or firefox.


https://user-images.githubusercontent.com/119693939/229165069-85aec613-b824-4d77-b5cc-be92f38f8fdc.mov

**Comment by JeffGreiner-eaton** [comment] 2023-04-03 18:48
closing this issue, it has been fixed. This latest from dev
https://blui-react-docs--pr743-bug-fix-undefined-im-ipix60vz.web.app/components/app-bar/playground
https://blui-react-docs--pr743-bug-fix-undefined-im-ipix60vz.web.app/components/drawer-header/playground

**Comment by JeffGreiner-eaton** [comment] 2023-04-03 19:07
This is haunting me

**Closed** 2023-04-05 18:25 UTC
Labels: bug, good first issue, brightlayer-ui
